name = "Ryan"
license = "MIT"
licenselink = "https://github.com/yangchuansheng/ryan/blob/master/LICENSE"
description = "Highly customizable open source theme for Hugo based static websites"
tags = ["blog", "company", "portfolio", "projects", "minimal", "responsive"]
features = ["blog", "themes", "disqus", "minimal", "responsive"]
min_version = 0.10

[author]
    name = "Ryan Yang"
    homepage = "https://www.yangcs.net"
